replies:
  - "Just in my pants - a moral position on underwear"
  - "Company mission: end football now, do your part"
  - "Our ideal holiday: cross dressing in Paris"
  - "FDS believe in unlimited poppadoms"
  - "V. plzd 2 announce FDS hd kidz, names are haddock, turbot and lemon sole"
  - "Ask us about our binary finger counting course - HIGH 31!! hahaha.."
  - "Buy a swan Pedalo and ride it pan-atlantic to Miami spring break 2015"
  - "Why not try our battenburger: battenburg and burger"
  - "Special deal on our clapping classes: $4,125 for 2 hours"
  - "The Foxdog is an almost invincible creature its only weakness is poor time management."
